config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  resource :sessions, only: [:create, :destroy]
  resources :users, param: :address
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 50

  has_one_attached :pfp do |attachable|
    attachable.variant :grid, resize_to_limit: [500, 500]
  end

  validates :eth_address, presence: true, uniqueness: true
  validates :bio, length: { maximum: 140 }
  validates :name, length: { maximum: 60 }
  validates :twitter_username, length: { maximum: 20 }
  validates :discord_username, length: { maximum: 20 }
  validate :valid_eth_address?

  before_create :checksum_address

  private
  def valid_eth_address?
    if eth_address && !Eth::Utils.valid_address?(eth_address)
      errors.add(:eth_address, I18n.t('errors.invalid_eth_address'))
    end
  end

  def checksum_address
    self.eth_address = Eth::Utils.format_address(eth_address)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    return unless session[:user_id]

    @current_user ||= User.find(session[:user_id])
  end

  def authenticate
    redirect_to root_url unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    if current_user
      redirect_to users_path
    else
      session[:nonce] = SecureRandom.hex(10)
    end
  end

  def create
    if valid_nonce? && valid_sig? && is_proof_member?
      user = User.find_or_initialize_by(eth_address: params[:address])

      if user.persisted?
        session[:user_id] = user.id

        redirect_to users_path
      else
        user.save
        session[:user_id] = user.id

        redirect_to edit_user_path(user.eth_address)
      end
    else
      render plain: 'no proof pass detected', status: :unauthorized
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_url
  end

  private
  def valid_nonce?
    nonce = params[:message][/.*<([^>]*)/,1]
    nonce == session[:nonce]
  end

  def valid_sig?
    recovered_key = Eth::Key.personal_recover(
      params[:message].delete("\r"), params[:sig]
    )

    Eth::Utils.public_key_to_address(recovered_key).downcase == params[:address].downcase
  end

  def is_proof_member?
    service = EtherscanService.new(api_key: Rails.application.credentials.etherscan.api_key)
    service.is_proof_member?(params[:address])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate
  before_action :authorize, only: [:edit, :update]
  before_action :find_user, except: :index

  def index
    @users = User.page(params[:page])
  end

  def show;end

  def edit;end

  def update
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  private

  def authorize
    head 401 if params[:address] != current_user.eth_address
  end

  def user_params
    params.require(:user).permit(:bio, :pfp, :name, :twitter_username, :discord_username)
  end

  def find_user
    @user = User.find_by!(eth_address: params[:address])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def name_or_address(user)
    user.name.presence || user.eth_address
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProofProfiles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href='//fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit Member</h1>
<div class='row user-edit'>
  <%= form_with model:  @user, url: user_path(@user.eth_address) do |form| %>
    <div class='column'>
      <div class='one-half column'>
        <%= label :name, t('prompts.user.name') %>
        <%= form.text_field :name, maxlength: 60 %>
        <% if @user.pfp.representable? %>
          <%= image_tag @user.pfp.representation(resize_to_limit: [200, 200])%>
        <% end %>
        <%= label :pfp, t('prompts.user.pfp') %>
        <%= form.file_field :pfp %>
        <%= label :twitter_username, t('prompts.user.twitter_username') %>
        <%= form.text_field :twitter_username, maxlength: 20 %>
        <%= label :discord_username, t('prompts.user.discord_username') %>
        <%= form.text_field :discord_username, maxlength: 20 %>
        <%= label :bio, t('prompts.user.bio') %>
        <%= form.text_area :bio, maxlength: 140, class: 'u-full-width' %>
      </div>
    </div>
    <div class='column'>
      <%= form.submit t('actions.update'), class: 'button-primary' %>
      <%= link_to t('actions.back'), users_path%>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Members</h1>
<span><%= "#{t('general.logged_in')} #{name_or_address(current_user)}" %></span> |
<%= link_to t('prompts.edit_profile'), edit_user_path(current_user.eth_address) %> |
<%= link_to t('prompts.contribute'), 'https://github.com/r4v3n-art/proof-profiles' %> |
<%= link_to t('prompts.logout'), sessions_path, data: { turbo_method: :delete } %>
<div class='users-container row'>
  <% @users.each do |user| %>
    <div class='user-block'>
      <% if user.pfp.representable? %>
        <%= image_tag user.pfp.representation(resize_to_limit: [500, 500]) %>
      <% else %>
          <%= image_tag 'kro-duck.jpg', width: 500 %>
      <% end %>
      <h4><%= name_or_address(user) %></h4>
      <p><%= user.bio %></p>
      <div>
        <% if user.twitter_username.present? %>
          <%= link_to image_tag('twitter.svg', class: 'twitter'), "https://www.twitter.com/#{user.twitter_username}" %>
          <span>@<%= user.twitter_username %></span>
        <% end %>
      </div>
      <div>
        <% if user.discord_username.present? %>
          <%= image_tag 'discord.svg', class: 'discord' %>
          <span><%= user.discord_username %></span>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= paginate @users %>
</div>